### ISSUE TITLE
undeclared variables

### ISSUE THREAD

**Issue by lucazade** [AndresCidoncha/audio-switcher#1]
I see these in journalctl:
giu 26 13:40:47 archos org.gnome.Shell.desktop[1045]: Gjs-Message: JS WARNING: [/home/luca/.local/share/gnome-shell/extensions/audio-switcher@AndresCidoncha/extension.js 95]: assignment to undeclared variable defsource
giu 26 13:40:47 archos org.gnome.Shell.desktop[1045]: Gjs-Message: JS WARNING: [/home/luca/.local/share/gnome-shell/extensions/audio-switcher@AndresCidoncha/extension.js 90]: assignment to undeclared variable item
giu 26 13:40:47 archos org.gnome.Shell.desktop[1045]: Gjs-Message: JS WARNING: [/home/luca/.local/share/gnome-shell/extensions/audio-switcher@AndresCidoncha/extension.js 31]: assignment to undeclared variable defsink
giu 26 13:40:47 archos org.gnome.Shell.desktop[1045]: Gjs-Message: JS WARNING: [/home/luca/.local/share/gnome-shell/extensions/TopIcons@phocean.net/extension.js 44]: assignment to undeclared variable trayIconImplementations

**Comment by AndresCidoncha** [comment]
Thank you lucazade! I think that it's fixed now. 
You can update the extension with a git pull in the directory.

**Comment by lucazade** [comment]
thanks!
