### ISSUE TITLE
Could someone update the current version to extensions.gnome.org ?

### ISSUE THREAD

**Issue by zelfir** [AndresCidoncha/audio-switcher#11]
Current distributions use Gnome 3.32, but the extension from extensions.gnome.org only supports up to Gnome 3.26. If someone could publish an updated (stable) version, that would be great.
Thanks.

**Comment by AndresCidoncha** [comment]
I'm sorry @zelfir, I just submitted the new version in gnome-extensions. Is waiting for review.

Thank you!

**Comment by AndresCidoncha** [comment]
I'll close this issue as the info in extensions.gnome.org have been updated
