### ISSUE TITLE
Gnome 3.34 support needed

### ISSUE THREAD

**Issue by zelfir** [AndresCidoncha/audio-switcher#15]
Gnome 3.34 is out since september, and we need support for it.
Could you please add gnome 3.34 support ?
I would love to learn what's needed to do so, but it seems that adding the version number to the json file is not enough.

**Comment by AndresCidoncha** [comment]
Hi @zelfir,

In addition to add the version in the JSON file, I have to release a new version and upload it to the gnome-extensions website.

I'll do it in a few moments, as I want to start working on this again to fix the multiple issues opened.

Thanks for your time! (And sorry for the late response)

**Comment by AndresCidoncha** [comment]
The new version has been already published!
