### ISSUE TITLE
Initially the wrong audio device is selected

### ISSUE THREAD

**Issue by vanitasvitae** [AndresCidoncha/audio-switcher#16]
Hi!
Great extension, I use it on a daily basis and find it a valuable addition to the Gnome desktop. Thank you for your work!

There is one little issue: After logging in, my USB headset is selected by the extension. However, sound is coming from my loudspeakers. Changing volume does not change the loudspeaker volume then.
Only after selecting my loudspeakers in the audio switcher menu, I can control their volume again.

Keep up the great work!

**Comment by AndresCidoncha** [comment]
I'll try to give a look on this on these days! :)

**Comment by AndresCidoncha** [comment]
I tried to reproduce this issue but after logging with USB headset connected, sound comes from the headset. 
Is this still happenning to you? Can you give me more info about how to reproduce it?

**Comment by vanitasvitae** [comment]
I recently upgraded my system to gnome-shell 3.36.2 and the issue appears to be gone now.
