### ISSUE TITLE
Publish new versions to extensions.gnome.org?

### ISSUE THREAD

**Issue by goncalossilva** [AndresCidoncha/audio-switcher#6]
Latest seems to be for 3.24.

**Comment by AndresCidoncha** [comment]
Done! 😄

**Comment by goncalossilva** [comment]
That was fast! Something seems broken though. When I access https://extensions.gnome.org/extension/1092/audio-switcher/ I get a 404...

**Comment by AndresCidoncha** [comment]
Yes, to update the version support I had to upload the new version of metadata.json and now they have to approve it... I deactivate the previous version (misclick :sob: ) and it looks that we must wait now :(

EDIT: Fix it! :D

**Comment by goncalossilva** [comment]
:tada: 

Thanks! Awesome extension :ok_hand:
