### ISSUE TITLE
Error on GS 3.32 at startup

### ISSUE THREAD

**Issue by luca-viggiani** [AndresCidoncha/audio-switcher#9]
Tryed to install from gnome extensions page on GS 3.32.0 and got error

**Comment by AndresCidoncha** [comment]
Hello @luca-viggiani,

I've been able to replicate the error, but I'm not sure what's the problem. Installing the extension using git works for me:

`git clone git@github.com:AndresCidoncha/audio-switcher.git ~/.local/share/gnome-shell/extensions/audio-switcher@AndresCidoncha`

Sorry it took so long to get back to you, I don't have the notifications enabled for this repository.
